/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.trackunit.cart.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2022-10-04T02:30:24.278128-04:00[America/Toronto]")
@Validated
@Tag(name = "item", description = "the item API")
@RequestMapping("${openapi.shoppintCartService.base-path:/api/v1}")
public interface ItemApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * PATCH /item/{itemId}
     * Remove item
     *
     * @param itemId Item ID (required)
     * @return Version history (status code 200)
     */
    @Operation(
            operationId = "removeItem",
            responses = {
                    @ApiResponse(responseCode = "200", description = "Version history")
            }
    )
    @RequestMapping(
            method = RequestMethod.PATCH,
            value = "/item/{itemId}"
    )
    default ResponseEntity<Void> removeItem(
            @Min(0) @Parameter(name = "itemId", description = "Item ID", required = true) @PathVariable("itemId") Integer itemId
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
